In [2]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('/home/arunaviyer/Desktop/worldcup_predictor/data/results.csv')

df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [5]:
df.shape

(49477, 9)

In [6]:
df['date'] = pd.to_datetime(df['date'])

## Using the result data of the last 20 years 

df = df[df['date']>'2006-01-01']

df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
29732,2006-01-02,Qatar,Libya,2.0,0.0,Friendly,Doha,Qatar,False
29733,2006-01-05,Egypt,Zimbabwe,2.0,0.0,Friendly,Alexandria,Egypt,False
29734,2006-01-07,Guinea,Togo,1.0,0.0,Friendly,Viry-Châtillon,France,True
29735,2006-01-09,Morocco,DR Congo,3.0,0.0,Friendly,Rabat,Morocco,False
29736,2006-01-11,Ghana,Togo,0.0,1.0,Friendly,Monastir,Tunisia,True

In [7]:
null_counts = df.isnull().sum()
print(null_counts)

date           0
home_team      0
away_team      0
home_score    44
away_score    44
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [8]:
rows_with_nulls = df[df.isnull().any(axis=1)]
print(rows_with_nulls.head())

            date      home_team    away_team  home_score  away_score  \
49433 2026-06-19       Scotland      Morocco         NaN         NaN
49434 2026-06-19         Brazil        Haiti         NaN         NaN
49435 2026-06-19  United States    Australia         NaN         NaN
49436 2026-06-19         Turkey     Paraguay         NaN         NaN
49437 2026-06-20        Germany  Ivory Coast         NaN         NaN

           tournament          city        country  neutral
49433  FIFA World Cup    Foxborough  United States     True
49434  FIFA World Cup  Philadelphia  United States     True
49435  FIFA World Cup       Seattle  United States    False
49436  FIFA World Cup   Santa Clara  United States     True
49437  FIFA World Cup       Toronto         Canada     True

In [9]:
df = df.dropna()

df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [10]:
print(df['date'].dtype)

datetime64[us]

In [11]:
## Creating target variable 

def get_result(row):
    if row['home_score']>row['away_score']:
        return 2
    elif row['home_score']==row['away_score']:
        return 1
    else:
        return 0
    
df['result'] = df.apply(get_result,axis=1)

In [12]:
df.head(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result
29732,2006-01-02,Qatar,Libya,2.0,0.0,Friendly,Doha,Qatar,False,2
29733,2006-01-05,Egypt,Zimbabwe,2.0,0.0,Friendly,Alexandria,Egypt,False,2
29734,2006-01-07,Guinea,Togo,1.0,0.0,Friendly,Viry-Châtillon,France,True,2
29735,2006-01-09,Morocco,DR Congo,3.0,0.0,Friendly,Rabat,Morocco,False,2
29736,2006-01-11,Ghana,Togo,0.0,1.0,Friendly,Monastir,Tunisia,True,0
29737,2006-01-12,Tunisia,Libya,1.0,0.0,Friendly,Tunis,Tunisia,False,2
29738,2006-01-14,Egypt,South Africa,1.0,2.0,Friendly,Cairo,Egypt,False,0
29739,2006-01-14,Morocco,Zimbabwe,1.0,0.0,Friendly,Marrakesh,Morocco,False,2
29740,2006-01-14,Senegal,DR Congo,0.0,0.0,Friendly,Dakar,Senegal,False,1
29741,2006-01-15,Tunisia,Ghana,2.0,0.0,Friendly,Tunis,Tunisia,False,2

In [13]:
df.dtypes

date          datetime64[us]
home_team                str
away_team                str
home_score           float64
away_score           float64
tournament               str
city                     str
country                  str
neutral                 bool
result                 int64
dtype: object

In [14]:
print(df['result'].value_counts())

result
2    9451
0    5683
1    4567
Name: count, dtype: int64

In [15]:
print(df['result'].value_counts(normalize=True)*100)

result
2    47.972184
0    28.846251
1    23.181564
Name: proportion, dtype: float64

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19701 entries, 29732 to 49432
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        19701 non-null  datetime64[us]
 1   home_team   19701 non-null  str
 2   away_team   19701 non-null  str
 3   home_score  19701 non-null  float64
 4   away_score  19701 non-null  float64
 5   tournament  19701 non-null  str
 6   city        19701 non-null  str
 7   country     19701 non-null  str
 8   neutral     19701 non-null  bool
 9   result      19701 non-null  int64
dtypes: bool(1), datetime64[us](1), float64(2), int64(1), str(5)
memory usage: 1.4 MB

In [17]:
## Sort the data according to the date

df = df.sort_values('date')

df = df.reset_index(drop=True)

In [18]:
df.head(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result
0,2006-01-02,Qatar,Libya,2.0,0.0,Friendly,Doha,Qatar,False,2
1,2006-01-05,Egypt,Zimbabwe,2.0,0.0,Friendly,Alexandria,Egypt,False,2
2,2006-01-07,Guinea,Togo,1.0,0.0,Friendly,Viry-Châtillon,France,True,2
3,2006-01-09,Morocco,DR Congo,3.0,0.0,Friendly,Rabat,Morocco,False,2
4,2006-01-11,Ghana,Togo,0.0,1.0,Friendly,Monastir,Tunisia,True,0
5,2006-01-12,Tunisia,Libya,1.0,0.0,Friendly,Tunis,Tunisia,False,2
6,2006-01-14,Morocco,Zimbabwe,1.0,0.0,Friendly,Marrakesh,Morocco,False,2
7,2006-01-14,Senegal,DR Congo,0.0,0.0,Friendly,Dakar,Senegal,False,1
8,2006-01-14,Egypt,South Africa,1.0,2.0,Friendly,Cairo,Egypt,False,0
9,2006-01-15,Tunisia,Ghana,2.0,0.0,Friendly,Tunis,Tunisia,False,2

In [19]:
## We will calculate the team form over the last 5 matches 
team_history={}

home_win_rate=[]

away_win_rate=[]

home_avg_goals=[]

away_avg_goals=[]

home_avg_conceded=[]

away_avg_conceded=[]

In [20]:
def get_team_stats(history):
    if len(history)==0:
        return 0.5,0,0
    
    
    wins = 0
    goals_scored = 0
    goals_conceded = 0

    for match in history:
        wins += match['win']
        goals_scored += match['scored']
        goals_conceded += match['conceded']

    n = len(history)

    return (
        wins/n,
        goals_scored/n,
        goals_conceded/n
    )

In [21]:
for idx,row in df.iterrows():

    home=row['home_team']
    away=row['away_team']


    home_history=team_history.get(home,[])

    away_history=team_history.get(away,[])


    home_last5=home_history[-5:]

    away_last5=away_history[-5:]


    h_win,h_goal,h_con=get_team_stats(home_last5)

    a_win,a_goal,a_con=get_team_stats(away_last5)


    home_win_rate.append(h_win)

    away_win_rate.append(a_win)

    home_avg_goals.append(h_goal)

    away_avg_goals.append(a_goal)

    home_avg_conceded.append(h_con)

    away_avg_conceded.append(a_con)


    #----------------------------------

    home_win=1 if row['home_score']>row['away_score'] else 0

    away_win=1 if row['away_score']>row['home_score'] else 0


    home_match={

        'win':home_win,

        'scored':row['home_score'],

        'conceded':row['away_score']

    }


    away_match={

        'win':away_win,

        'scored':row['away_score'],

        'conceded':row['home_score']

    }


    team_history.setdefault(home,[]).append(home_match)

    team_history.setdefault(away,[]).append(away_match)

In [22]:
print(len(home_win_rate))

print(len(df))

19701
19701

In [23]:
df['home_win_rate']=home_win_rate

df['away_win_rate']=away_win_rate


df['home_avg_goals']=home_avg_goals

df['away_avg_goals']=away_avg_goals


df['home_avg_conceded']=home_avg_conceded

df['away_avg_conceded']=away_avg_conceded

In [24]:
df[[
'home_team',

'away_team',

'home_win_rate',

'away_win_rate',

'home_avg_goals',

'away_avg_goals',

'home_avg_conceded',

'away_avg_conceded'

]].head(20)

,home_team,away_team,home_win_rate,away_win_rate,home_avg_goals,away_avg_goals,home_avg_conceded,away_avg_conceded
0,Qatar,Libya,0.500000,0.5,0.0,0.0,0.000000,0.0
1,Egypt,Zimbabwe,0.500000,0.5,0.0,0.0,0.000000,0.0
2,Guinea,Togo,0.500000,0.5,0.0,0.0,0.000000,0.0
3,Morocco,DR Congo,0.500000,0.5,0.0,0.0,0.000000,0.0
4,Ghana,Togo,0.500000,0.0,0.0,0.0,0.000000,1.0
5,Tunisia,Libya,0.500000,0.0,0.0,0.0,0.000000,2.0
6,Morocco,Zimbabwe,1.000000,0.0,3.0,0.0,0.000000,2.0
7,Senegal,DR Congo,0.500000,0.0,0.0,0.0,0.000000,3.0
8,Egypt,South Africa,1.000000,0.5,2.0,0.0,0.000000,0.0
9,Tunisia,Ghana,1.000000,0.0,1.0,0.0,0.000000,1.0
10,Ivory Coast,Jordan,0.500000,0.5,0.0,0.0,0.000000,0.0
11,Morocco,Angola,1.000000,0.5,2.0,0.0,0.000000,0.0
12,Saudi Arabia,Sweden,0.500000,0.5,0.0,0.0,0.000000,0.0
13,United Arab Emirates,South Korea,0.500000,0.5,0.0,0.0,0.000000,0.0
14,Egypt,Libya,0.500000,0.0,1.5,0.0,1.000000,1.5
15,Togo,DR Congo,0.500000,0.0,0.5,0.0,0.500000,1.5
16,Morocco,Ivory Coast,0.666667,1.0,2.0,2.0,0.666667,0.0
17,Saudi Arabia,Finland,0.000000,0.5,1.0,0.0,1.000000,0.0
18,Cameroon,Angola,0.500000,0.0,0.0,2.0,0.000000,2.0
19,Greece,South Korea,0.500000,0.0,0.0,0.0,0.000000,1.0

In [25]:
df.tail(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,home_win_rate,away_win_rate,home_avg_goals,away_avg_goals,home_avg_conceded,away_avg_conceded
19691,2026-06-16,Argentina,Algeria,3.0,0.0,FIFA World Cup,Kansas City,United States,True,2,1.0,0.6,2.8,2.4,0.2,0.4
19692,2026-06-16,Austria,Jordan,3.0,1.0,FIFA World Cup,Santa Clara,United States,True,2,0.8,0.0,2.0,1.4,0.4,2.6
19693,2026-06-17,England,Croatia,4.0,2.0,FIFA World Cup,Arlington,United States,True,2,0.6,0.6,1.4,1.6,0.4,1.8
19694,2026-06-17,Ghana,Panama,1.0,0.0,FIFA World Cup,Toronto,Canada,True,2,0.0,0.4,0.6,2.0,2.2,2.2
19695,2026-06-17,Portugal,DR Congo,1.0,1.0,FIFA World Cup,Houston,United States,True,1,0.8,0.4,3.0,0.8,0.6,0.6
19696,2026-06-17,Uzbekistan,Colombia,1.0,3.0,FIFA World Cup,Mexico City,Mexico,True,0,0.2,0.6,1.2,2.0,1.4,1.2
19697,2026-06-18,Mexico,South Korea,1.0,0.0,FIFA World Cup,Zapopan,Mexico,False,2,0.8,0.6,2.2,1.6,0.4,1.2
19698,2026-06-18,Switzerland,Bosnia and Herzegovina,4.0,1.0,FIFA World Cup,Inglewood,United States,True,2,0.2,0.0,1.8,0.8,1.4,0.8
19699,2026-06-18,Czech Republic,South Africa,1.0,1.0,FIFA World Cup,Atlanta,United States,True,1,0.4,0.2,2.4,0.6,1.6,1.0
19700,2026-06-18,Canada,Qatar,6.0,0.0,FIFA World Cup,Vancouver,Canada,False,2,0.2,0.0,1.2,0.4,0.8,1.2

In [26]:
team_history['Morocco']

[{'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 6.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 5.0, 'conceded': 1.0},
 {'win': 0, 'scored': 2.0, 'conceded': 3.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 3.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 3.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 0, 'scored': 2.0, 'conceded': 3.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 0, 'scored': 0.0, 'conceded': 4.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 0, 'scored': 1.0, 'conceded': 3.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 6.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 1, 'scored': 6.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 1.0},
 {'win': 0, 'scored': 2.0, 'conceded': 3.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 2.0, 'conceded': 3.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 5.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 2.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 3.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 2.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 2.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 6.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 1.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 5.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 1, 'scored': 5.0, 'conceded': 1.0},
 {'win': 1, 'scored': 7.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 5.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 1.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 2.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 1, 'scored': 1.0, 'conceded': 0.0},
 {'win': 1, 'scored': 2.0, 'conceded': 0.0},
 {'win': 0, 'scored': 0.0, 'conceded': 0.0},
 {'win': 1, 'scored': 3.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 1, 'scored': 2.0, 'conceded': 1.0},
 {'win': 1, 'scored': 5.0, 'conceded': 0.0},
 {'win': 1, 'scored': 4.0, 'conceded': 0.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0},
 {'win': 0, 'scored': 1.0, 'conceded': 1.0}]

In [27]:
## Creating DIfference features

df['win_rate_diff'] = df['home_win_rate'] - df['away_win_rate']

df['avg_goals_diff'] = df['home_avg_goals'] - df['away_avg_goals']

df['avg_conceded_diff'] = (df['home_avg_conceded']-df['away_avg_conceded'])

In [28]:
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,home_win_rate,away_win_rate,home_avg_goals,away_avg_goals,home_avg_conceded,away_avg_conceded,win_rate_diff,avg_goals_diff,avg_conceded_diff
19696,2026-06-17,Uzbekistan,Colombia,1.0,3.0,FIFA World Cup,Mexico City,Mexico,True,0,0.2,0.6,1.2,2.0,1.4,1.2,-0.4,-0.8,0.2
19697,2026-06-18,Mexico,South Korea,1.0,0.0,FIFA World Cup,Zapopan,Mexico,False,2,0.8,0.6,2.2,1.6,0.4,1.2,0.2,0.6,-0.8
19698,2026-06-18,Switzerland,Bosnia and Herzegovina,4.0,1.0,FIFA World Cup,Inglewood,United States,True,2,0.2,0.0,1.8,0.8,1.4,0.8,0.2,1.0,0.6
19699,2026-06-18,Czech Republic,South Africa,1.0,1.0,FIFA World Cup,Atlanta,United States,True,1,0.4,0.2,2.4,0.6,1.6,1.0,0.2,1.8,0.6
19700,2026-06-18,Canada,Qatar,6.0,0.0,FIFA World Cup,Vancouver,Canada,False,2,0.2,0.0,1.2,0.4,0.8,1.2,0.2,0.8,-0.4

In [29]:
## Creating home advantage column as this plays a huge role 

df['neutral'] = df['neutral'].astype(int)

df['neutral']

0        0
1        0
2        1
3        0
4        1
        ..
19696    1
19697    0
19698    1
19699    1
19700    0
Name: neutral, Length: 19701, dtype: int64

In [30]:
df['home_advantage'] = 1 - df['neutral']

df['home_advantage']

0        1
1        1
2        0
3        1
4        0
        ..
19696    0
19697    1
19698    0
19699    0
19700    1
Name: home_advantage, Length: 19701, dtype: int64

In [31]:
print(df['tournament'].unique())

<StringArray>
[                                         'Friendly',
                            'African Cup of Nations',
                                'Lunar New Year Cup',
                       'AFC Asian Cup qualification',
                   'Cyprus International Tournament',
                    'Malta International Tournament',
                                      'Muratti Vase',
                                 'AFC Challenge Cup',
                                        'COSAFA Cup',
                                         'Kirin Cup',
 ...
                                         'Unity Cup',
                                   'Canadian Shield',
                           'Outrigger Challenge Cup',
                             'South Asian Super Cup',
                                   'CONCACAF Series',
                          'Al Ain International Cup',
              'Morocco, Capital of African Football',
                                  'Mukuru 4 Nations',
 'Diamond Jubilee International Football Tournament',
                                   'Tri-Nations Cup']
Length: 115, dtype: str

In [32]:
## As a FRIENDLY game is not same as a FIFA WORLD CUP game and a QUALIFIER game i will make 3 separate features 

df['is_friendly'] = (df['tournament']=='Friendly').astype(int)

df['is_worldcup'] = (df['tournament']=='FIFA World Cup').astype(int)

df['is_qualifier'] = (df['tournament']=='FIFA World Cup qualification').astype(int)

In [33]:
df[['tournament','is_friendly','is_worldcup','is_qualifier']].head(10)

  tournament  is_friendly  is_worldcup  is_qualifier
0   Friendly            1            0             0
1   Friendly            1            0             0
2   Friendly            1            0             0
3   Friendly            1            0             0
4   Friendly            1            0             0
5   Friendly            1            0             0
6   Friendly            1            0             0
7   Friendly            1            0             0
8   Friendly            1            0             0
9   Friendly            1            0             0

In [34]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral', 'result', 'home_win_rate',
       'away_win_rate', 'home_avg_goals', 'away_avg_goals',
       'home_avg_conceded', 'away_avg_conceded', 'win_rate_diff',
       'avg_goals_diff', 'avg_conceded_diff', 'home_advantage', 'is_friendly',
       'is_worldcup', 'is_qualifier'],
      dtype='str')

In [35]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,result,...,away_avg_goals,home_avg_conceded,away_avg_conceded,win_rate_diff,avg_goals_diff,avg_conceded_diff,home_advantage,is_friendly,is_worldcup,is_qualifier
0,2006-01-02,Qatar,Libya,2.0,0.0,Friendly,Doha,Qatar,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,1,1,0,0
1,2006-01-05,Egypt,Zimbabwe,2.0,0.0,Friendly,Alexandria,Egypt,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,1,1,0,0
2,2006-01-07,Guinea,Togo,1.0,0.0,Friendly,Viry-Châtillon,France,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0
3,2006-01-09,Morocco,DR Congo,3.0,0.0,Friendly,Rabat,Morocco,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,1,1,0,0
4,2006-01-11,Ghana,Togo,0.0,1.0,Friendly,Monastir,Tunisia,1,0,...,0.0,0.0,1.0,0.5,0.0,-1.0,0,1,0,0

In [36]:
## NOw we will add elo ratings of the team which will boost the models prediction accuracy 

elo = {}

home_elo = []
away_elo = []

In [37]:
## I will take a intermediate value of K=30 not too large not too small 

K = 30 

for idx,row in df.iterrows():
    home = row['home_team']
    away = row['away_team']

    home_rating = elo.get(home,1500)
    away_rating = elo.get(away,1500)

    home_elo.append(home_rating)
    away_elo.append(away_rating)

    expected_home = 1/(1+10**((away_rating-home_rating)/400))
    expected_away = 1 - expected_home

    if row['home_score']>row['away_score']:
        actual_home = 1
        actual_away = 0
    elif row['home_score']==row['away_score']:
        actual_home = 0.5
        actual_away = 0.5
    else:
        actual_home = 0
        actual_away = 1
    
    new_home = home_rating + K*(actual_home-expected_home)
    new_away = away_rating + K*(actual_away-expected_away)

    elo[home] = new_home
    elo[away] = new_away

In [38]:
print(len(home_elo))
print(len(df))

19701
19701

In [39]:
df['home_elo'] = home_elo
df['away_elo'] = away_elo

In [40]:
df['elo_diff'] = df['home_elo'] - df['away_elo']

In [41]:
df[['home_team','away_team','home_elo','away_elo','elo_diff']].tail(20)

,home_team,away_team,home_elo,away_elo,elo_diff
19681,Germany,Curaçao,1868.900630,1526.716315,342.184315
19682,Ivory Coast,Ecuador,1752.575909,1837.878192,-85.302283
19683,Netherlands,Japan,1845.120094,1878.259604,-33.139510
19684,Sweden,Tunisia,1672.487472,1668.245597,4.241875
19685,Saudi Arabia,Uruguay,1649.413901,1798.135246,-148.721345
19686,Belgium,Egypt,1810.699255,1739.818273,70.880981
19687,Iran,New Zealand,1812.064998,1596.842992,215.222007
19688,Spain,Cape Verde,1971.171686,1605.246564,365.925122
19689,France,Senegal,1913.536732,1797.759054,115.777678
19690,Iraq,Norway,1695.265636,1765.811477,-70.545841
19691,Argentina,Algeria,1983.087025,1813.892140,169.194885
19692,Austria,Jordan,1766.654088,1666.363834,100.290255
19693,England,Croatia,1873.932609,1813.143693,60.788916
19694,Ghana,Panama,1554.122921,1701.747510,-147.624589
19695,Portugal,DR Congo,1883.411441,1662.659215,220.752226
19696,Uzbekistan,Colombia,1736.156000,1872.302607,-136.146607
19697,Mexico,South Korea,1840.204044,1809.666419,30.537625
19698,Switzerland,Bosnia and Herzegovina,1770.562326,1562.930490,207.631836
19699,Czech Republic,South Africa,1685.608441,1627.388339,58.220102
19700,Canada,Qatar,1769.059697,1581.814931,187.244765

In [42]:
## Creating columns for avg goal diff in last 5 matches indicating their form 

home_goal_diff_form = []
away_goal_diff_form = []

team_history2 = {}

In [43]:
for idx,row in df.iterrows():
    home = row['home_team']
    away = row['away_team']

    home_hist = team_history2.get(home,[])[-5:]
    away_hist = team_history2.get(away,[])[-5:]

    if len(home_hist)==0:
        home_goal_diff_form.append(0)
    else:
        gd = sum(home_hist)/len(home_hist)
        home_goal_diff_form.append(gd)

    if len(away_hist)==0:
        away_goal_diff_form.append(0)
    else:
        gd = sum(away_hist)/len(away_hist)
        away_goal_diff_form.append(gd)

    
    current_home_gd=row['home_score']-row['away_score']
    current_away_gd=row['away_score']-row['home_score']

    team_history2.setdefault(home,[]).append(current_home_gd)
    team_history2.setdefault(away,[]).append(current_away_gd)

In [44]:
df['home_goal_diff_form']=home_goal_diff_form

df['away_goal_diff_form']=away_goal_diff_form

df['goal_diff_form_diff']=(df['home_goal_diff_form']-df['away_goal_diff_form'])

In [45]:
df[[
'home_team',
'away_team',
'home_goal_diff_form',
'away_goal_diff_form',
'goal_diff_form_diff'
]].tail(10)

,home_team,away_team,home_goal_diff_form,away_goal_diff_form,goal_diff_form_diff
19691,Argentina,Algeria,2.6,2.0,0.6
19692,Austria,Jordan,1.6,-1.2,2.8
19693,England,Croatia,1.0,-0.2,1.2
19694,Ghana,Panama,-1.6,-0.2,-1.4
19695,Portugal,DR Congo,2.4,0.2,2.2
19696,Uzbekistan,Colombia,-0.2,0.8,-1.0
19697,Mexico,South Korea,1.8,0.4,1.4
19698,Switzerland,Bosnia and Herzegovina,0.4,0.0,0.4
19699,Czech Republic,South Africa,0.8,-0.4,1.2
19700,Canada,Qatar,0.4,-0.8,1.2

In [46]:
df['elo_diff_squared'] = df['elo_diff']**2

In [47]:
print(df.columns)

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral', 'result', 'home_win_rate',
       'away_win_rate', 'home_avg_goals', 'away_avg_goals',
       'home_avg_conceded', 'away_avg_conceded', 'win_rate_diff',
       'avg_goals_diff', 'avg_conceded_diff', 'home_advantage', 'is_friendly',
       'is_worldcup', 'is_qualifier', 'home_elo', 'away_elo', 'elo_diff',
       'home_goal_diff_form', 'away_goal_diff_form', 'goal_diff_form_diff',
       'elo_diff_squared'],
      dtype='str')

In [48]:
print(len(df.columns))

30

In [49]:
features = [

'home_win_rate',
'away_win_rate',

'home_avg_goals',
'away_avg_goals',

'home_avg_conceded',
'away_avg_conceded',

'win_rate_diff',

'avg_goals_diff',

'avg_conceded_diff',

'home_advantage',

'is_friendly',

'is_worldcup',

'is_qualifier',

'home_elo',

'away_elo',

'elo_diff',

'elo_diff_squared'

]

In [50]:
df['elo_gap'] = abs(df['elo_diff'])
features.append('elo_gap')
df['form_gap'] = abs(df['win_rate_diff'])
features.append('form_gap')

In [51]:
print(len(features))

19

In [52]:
target='result'

In [53]:
df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral', 'result', 'home_win_rate',
       'away_win_rate', 'home_avg_goals', 'away_avg_goals',
       'home_avg_conceded', 'away_avg_conceded', 'win_rate_diff',
       'avg_goals_diff', 'avg_conceded_diff', 'home_advantage', 'is_friendly',
       'is_worldcup', 'is_qualifier', 'home_elo', 'away_elo', 'elo_diff',
       'home_goal_diff_form', 'away_goal_diff_form', 'goal_diff_form_diff',
       'elo_diff_squared', 'elo_gap', 'form_gap'],
      dtype='str')

In [54]:
features

['home_win_rate',
 'away_win_rate',
 'home_avg_goals',
 'away_avg_goals',
 'home_avg_conceded',
 'away_avg_conceded',
 'win_rate_diff',
 'avg_goals_diff',
 'avg_conceded_diff',
 'home_advantage',
 'is_friendly',
 'is_worldcup',
 'is_qualifier',
 'home_elo',
 'away_elo',
 'elo_diff',
 'elo_diff_squared',
 'elo_gap',
 'form_gap']

In [55]:
features

['home_win_rate',
 'away_win_rate',
 'home_avg_goals',
 'away_avg_goals',
 'home_avg_conceded',
 'away_avg_conceded',
 'win_rate_diff',
 'avg_goals_diff',
 'avg_conceded_diff',
 'home_advantage',
 'is_friendly',
 'is_worldcup',
 'is_qualifier',
 'home_elo',
 'away_elo',
 'elo_diff',
 'elo_diff_squared',
 'elo_gap',
 'form_gap']

In [56]:
train_df = df[df['date'] < '2023-01-01']

test_df = df[(df['date'] >= '2023-01-01') & (df['date'] < '2026-06-11')]

In [57]:
X_train = train_df[features]
y_train = train_df[target]

X_test = test_df[features]
y_test = test_df[target]

In [58]:
print(X_train.shape)

print(X_test.shape)

print(y_train.shape)

print(y_test.shape)

(16075, 19)
(3598, 19)
(16075,)
(3598,)

In [59]:
y_train.value_counts(normalize=True)

result
2    0.481244
0    0.286719
1    0.232037
Name: proportion, dtype: float64

In [60]:
print(X_train.dtypes)

home_win_rate        float64
away_win_rate        float64
home_avg_goals       float64
away_avg_goals       float64
home_avg_conceded    float64
away_avg_conceded    float64
win_rate_diff        float64
avg_goals_diff       float64
avg_conceded_diff    float64
home_advantage         int64
is_friendly            int64
is_worldcup            int64
is_qualifier           int64
home_elo             float64
away_elo             float64
elo_diff             float64
elo_diff_squared     float64
elo_gap              float64
form_gap             float64
dtype: object

In [61]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [62]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(16075, 19)
(3598, 19)

In [63]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=5000,
    random_state=42
)

lr.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=5000, random_state=42)

In [64]:
y_pred_lr = lr.predict(X_test_scaled)

In [65]:
from sklearn.metrics import accuracy_score

print(
    "Accuracy:",
    accuracy_score(y_test, y_pred_lr)
)

Accuracy: 0.6017231795441912

In [66]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_lr
    )
)

              precision    recall  f1-score   support

           0       0.57      0.65      0.60      1071
           1       0.45      0.01      0.01       827
           2       0.62      0.86      0.72      1700

    accuracy                           0.60      3598
   macro avg       0.55      0.51      0.45      3598
weighted avg       0.57      0.60      0.52      3598

In [67]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred_lr
)

print(cm)

[[ 691    1  379]
 [ 299    5  523]
 [ 226    5 1469]]

In [68]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=42)

In [69]:
y_pred_rf = rf.predict(X_test)

In [70]:
from sklearn.metrics import accuracy_score

print(
    accuracy_score(
        y_test,
        y_pred_rf
    )
)

0.5842134519177321

In [71]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred_rf
    )
)

              precision    recall  f1-score   support

           0       0.56      0.61      0.59      1071
           1       0.26      0.06      0.09       827
           2       0.62      0.83      0.71      1700

    accuracy                           0.58      3598
   macro avg       0.48      0.50      0.46      3598
weighted avg       0.52      0.58      0.53      3598

In [72]:
## Feature importance 

import pandas as pd

importance = pd.DataFrame({

    'feature':features,

    'importance':rf.feature_importances_

})

importance = importance.sort_values(
    'importance',
    ascending=False
)

print(importance)

              feature  importance
15           elo_diff    0.130627
14           away_elo    0.100107
13           home_elo    0.095756
17            elo_gap    0.085163
16   elo_diff_squared    0.084618
8   avg_conceded_diff    0.066761
7      avg_goals_diff    0.062003
4   home_avg_conceded    0.057330
5   away_avg_conceded    0.055962
2      home_avg_goals    0.054425
3      away_avg_goals    0.054002
6       win_rate_diff    0.032312
0       home_win_rate    0.027645
1       away_win_rate    0.027618
18           form_gap    0.024275
10        is_friendly    0.015242
9      home_advantage    0.013625
12       is_qualifier    0.010298
11        is_worldcup    0.002232

In [73]:
draws = df[df['result']==1]

non_draws = df[df['result']!=1]

print(draws['elo_gap'].mean())

print(non_draws['elo_gap'].mean())

95.60108436896421
122.84456394969008

In [74]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    objective='multi:softmax',
    num_class=3,

    n_estimators=300,
    max_depth=5,

    learning_rate=0.05,

    subsample=0.8,
    colsample_bytree=0.8,

    random_state=42
)

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_class=3, ...)

In [75]:
y_pred_xgb = xgb.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print(
    accuracy_score(
        y_test,
        y_pred_xgb
    )
)

print(
    classification_report(
        y_test,
        y_pred_xgb
    )
)

0.603112840466926
              precision    recall  f1-score   support

           0       0.58      0.65      0.61      1071
           1       0.36      0.04      0.07       827
           2       0.62      0.85      0.72      1700

    accuracy                           0.60      3598
   macro avg       0.52      0.51      0.47      3598
weighted avg       0.55      0.60      0.54      3598

In [77]:
importance = pd.DataFrame({
    'feature': features,
    'importance': xgb.feature_importances_
})

importance.sort_values(
    'importance',
    ascending=False,
    inplace=True
)

print(importance)

              feature  importance
15           elo_diff    0.186555
17            elo_gap    0.104387
16   elo_diff_squared    0.071567
9      home_advantage    0.071029
8   avg_conceded_diff    0.053800
14           away_elo    0.048159
10        is_friendly    0.045838
13           home_elo    0.045243
4   home_avg_conceded    0.037609
11        is_worldcup    0.036890
5   away_avg_conceded    0.036458
12       is_qualifier    0.035734
6       win_rate_diff    0.034112
7      avg_goals_diff    0.034062
18           form_gap    0.032474
2      home_avg_goals    0.032012
1       away_win_rate    0.031632
3      away_avg_goals    0.031319
0       home_win_rate    0.031121

In [78]:
import pickle

with open("worldcup_xgb.pkl","wb") as f:
    pickle.dump(xgb,f)


with open("features.pkl","wb") as f:
    pickle.dump(features,f)

In [79]:
latest_elo = {}

latest_form = {}

In [80]:
teams = set(df['home_team']).union(set(df['away_team']))

team_stats = {}

In [81]:
teams

{'Abkhazia',
 'Afghanistan',
 'Albania',
 'Alderney',
 'Algeria',
 'Ambazonia',
 'American Samoa',
 'Andalusia',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Arameans Suryoye',
 'Argentina',
 'Armenia',
 'Artsakh',
 'Aruba',
 'Australia',
 'Austria',
 'Aymara',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barawa',
 'Barbados',
 'Basque Country',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Biafra',
 'Bolivia',
 'Bonaire',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brittany',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Canary Islands',
 'Cape Verde',
 'Cascadia',
 'Catalonia',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chagos Islands',
 'Chameria',
 'Chechnya',
 'Chile',
 'China',
 'Cilento',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Corsica',
 'Costa Rica',
 'County of Nice',
 'Crimea',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'DR Congo',
 'Darfur',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Donetsk PR',
 'Délvidék',
 'East Turkestan',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Elba Island',
 'Ellan Vannin',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Felvidék',
 'Fiji',
 'Finland',
 'France',
 'Franconia',
 'French Guiana',
 'Frøya',
 'Gabon',
 'Galicia',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Gotland',
 'Gozo',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Găgăuzia',
 'Haiti',
 'Hitra',
 'Hmong',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Iraqi Kurdistan',
 'Isle of Man',
 'Isle of Wight',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kabylia',
 'Kazakhstan',
 'Kenya',
 'Kernow',
 'Kiribati',
 'Kosovo',
 'Kurdistan',
 'Kuwait',
 'Kyrgyzstan',
 'Kárpátalja',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luhansk PR',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Madrid',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mapuche',
 'Marshall Islands',
 'Martinique',
 'Matabeleland',
 'Maule Sur',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Menorca',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Occitania',
 'Oman',
 'Orkney',
 'Padania',
 'Pakistan',
 'Palestine',
 'Panama',
 'Panjab',
 'Papua New Guinea',
 'Paraguay',
 'Parishes of Jersey',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Provence',
 'Puerto Rico',
 'Qatar',
 'Quebec',
 'Raetia',
 'Republic of Ireland',
 'Republic of St. Pauli',
 'Rhodes',
 'Romani people',
 'Romania',
 'Russia',
 'Rwanda',
 'Ryūkyū',
 'Réunion',
 'Saare County',
 'Saint Barthélemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Saugeais',
 'Scotland',
 'Sealand',
 'Seborga',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Shetland',
 'Sierra Leone',
 'Silesia',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Korea',
 'South Ossetia',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Surrey',
 'Sweden',
 'Switzerland',
 'Syria',
 'Székely Land',
 'Sápmi',
 'São Tomé and Príncipe',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tamil Eelam',
 'Tanzania',
 'Thailand',
 'Tibet',
 'Ticino',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Two Sicilies',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Koreans in Japan',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Wales',
 'West Papua',
 'Western Armenia',
 'Western Isles',
 'Western Sahara',
 'Yemen',
 'Ynys Môn',
 'Yorkshire',
 'Yoruba Nation',
 'Zambia',
 'Zanzibar',
 'Zimbabwe',
 'Åland Islands'}

In [82]:
for team in teams:
    home_matches = df[df['home_team']==team]
    away_matches = df[df['away_team']==team]

    matches = pd.concat([home_matches,away_matches])

    matches = matches.sort_values('date')

    last_match = matches.iloc[-1]

    if last_match['home_team']==team:
        elo = last_match['home_elo']
        win_rate = last_match['home_win_rate']
        avg_goals = last_match['home_avg_goals']
        avg_conceded = last_match['home_avg_conceded']
    else:
        elo = last_match['away_elo']
        win_rate = last_match['away_win_rate']
        avg_goals = last_match['away_avg_goals']
        avg_conceded = last_match['away_avg_conceded']

    team_stats[team] = {
        'elo':elo,
        'win_rate' : win_rate,
        'avg_goals' : avg_goals,
        'avg_conceded' : avg_conceded
    }

In [83]:
features

['home_win_rate',
 'away_win_rate',
 'home_avg_goals',
 'away_avg_goals',
 'home_avg_conceded',
 'away_avg_conceded',
 'win_rate_diff',
 'avg_goals_diff',
 'avg_conceded_diff',
 'home_advantage',
 'is_friendly',
 'is_worldcup',
 'is_qualifier',
 'home_elo',
 'away_elo',
 'elo_diff',
 'elo_diff_squared',
 'elo_gap',
 'form_gap']

In [84]:
team_stats['Brazil']

{'elo': np.float64(1890.0906556888792),
 'win_rate': np.float64(0.6),
 'avg_goals': np.float64(2.6),
 'avg_conceded': np.float64(1.4)}

In [87]:
team_stats['France']

{'elo': np.float64(1913.536732161188),
 'win_rate': np.float64(0.8),
 'avg_goals': np.float64(2.4),
 'avg_conceded': np.float64(1.2)}

In [86]:
team_stats['Morocco']

{'elo': np.float64(1886.3079261542161),
 'win_rate': np.float64(0.6),
 'avg_goals': np.float64(2.6),
 'avg_conceded': np.float64(0.6)}

In [92]:
team_stats['Netherlands']

{'elo': np.float64(1845.1200940572949),
 'win_rate': np.float64(0.6),
 'avg_goals': np.float64(1.8),
 'avg_conceded': np.float64(0.8)}

In [89]:
team_stats['Japan']

{'elo': np.float64(1878.2596041635827),
 'win_rate': np.float64(1.0),
 'avg_goals': np.float64(1.6),
 'avg_conceded': np.float64(0.0)}

In [91]:
team_stats['Argentina']

{'elo': np.float64(1983.0870247710907),
 'win_rate': np.float64(1.0),
 'avg_goals': np.float64(2.8),
 'avg_conceded': np.float64(0.2)}

In [90]:
team_stats['England']

{'elo': np.float64(1873.9326093746392),
 'win_rate': np.float64(0.6),
 'avg_goals': np.float64(1.4),
 'avg_conceded': np.float64(0.4)}

In [88]:
team_stats['Portugal']

{'elo': np.float64(1883.4114414532178),
 'win_rate': np.float64(0.8),
 'avg_goals': np.float64(3.0),
 'avg_conceded': np.float64(0.6)}

In [93]:
team_stats['Mexico']

{'elo': np.float64(1840.204044067629),
 'win_rate': np.float64(0.8),
 'avg_goals': np.float64(2.2),
 'avg_conceded': np.float64(0.4)}

In [94]:
team_stats['Norway']

{'elo': np.float64(1765.8114767753457),
 'win_rate': np.float64(0.4),
 'avg_goals': np.float64(1.8),
 'avg_conceded': np.float64(1.0)}

In [130]:
team_stats['Germany']

{'elo': np.float64(1868.9006304070676),
 'win_rate': np.float64(1.0),
 'avg_goals': np.float64(3.6),
 'avg_conceded': np.float64(1.0)}

In [85]:
team_stats['Spain']

{'elo': np.float64(1971.1716860976032),
 'win_rate': np.float64(0.4),
 'avg_goals': np.float64(1.8),
 'avg_conceded': np.float64(0.8)}

In [132]:
team_stats['Croatia']

{'elo': np.float64(1813.1436933358832),
 'win_rate': np.float64(0.6),
 'avg_goals': np.float64(1.6),
 'avg_conceded': np.float64(1.8)}

In [131]:
team_stats["Argentina"]["elo"] = 1988
team_stats["France"]["elo"] = 1976

team_stats["Spain"]["elo"] = 1965

team_stats["Portugal"]["elo"] = 1926

team_stats["England"]["elo"] = 1900

team_stats["Morocco"]["elo"] = 1870

team_stats["Mexico"]["elo"] = 1878

team_stats["Norway"]["elo"] = 1800

team_stats['Japan']['elo'] = 1820

team_stats['Germany']['elo'] = 1915

In [133]:
team_stats["Argentina"].update({
    "elo": 1988,
    "win_rate": 0.95,
    "avg_goals": 2.8,
    "avg_conceded": 0.30
})

team_stats["France"].update({
    "elo": 1985,
    "win_rate": 0.94,
    "avg_goals": 2.7,
    "avg_conceded": 0.35
})

team_stats["Spain"].update({
    "elo": 1965,
    "win_rate": 0.92,
    "avg_goals": 2.6,
    "avg_conceded": 0.45
})

team_stats["Portugal"].update({
    "elo": 1926,
    "win_rate": 0.90,
    "avg_goals": 2.5,
    "avg_conceded": 0.55
})

team_stats["England"].update({
    "elo": 1900,
    "win_rate": 0.89,
    "avg_goals": 2.4,
    "avg_conceded": 0.60
})

team_stats["Brazil"].update({
    "elo": 1890,
    "win_rate": 0.88,
    "avg_goals": 2.4,
    "avg_conceded": 0.65
})

team_stats["Morocco"].update({
    "elo": 1870,
    "win_rate": 0.83,
    "avg_goals": 2.1,
    "avg_conceded": 0.75
})

team_stats["Netherlands"].update({
    "elo": 1865,
    "win_rate": 0.82,
    "avg_goals": 2.1,
    "avg_conceded": 0.80
})

team_stats["Mexico"].update({
    "elo": 1840,
    "win_rate": 0.78,
    "avg_goals": 1.9,
    "avg_conceded": 0.95
})

team_stats["Norway"].update({
    "elo": 1822,
    "win_rate": 0.77,
    "avg_goals": 1.9,
    "avg_conceded": 1.00
})

In [134]:
print(len(team_stats))

319

In [135]:
print(list(team_stats.keys())[:20])

['Vanuatu', 'Japan', 'Oman', 'Ivory Coast', 'Canada', 'Kabylia', 'Tanzania', 'Saint Martin', 'France', 'Somalia', 'Yemen', 'Quebec', 'Réunion', 'Yoruba Nation', 'Sealand', 'Guadeloupe', 'Andorra', 'Catalonia', 'Mongolia', 'French Guiana']

In [136]:
print(len(features))

19

In [137]:
team_stats['Morocco']

{'elo': 1870, 'win_rate': 0.83, 'avg_goals': 2.1, 'avg_conceded': 0.75}

In [138]:
team_stats['Argentina']

{'elo': 1988, 'win_rate': 0.95, 'avg_goals': 2.8, 'avg_conceded': 0.3}

In [139]:
print(features)

['home_win_rate', 'away_win_rate', 'home_avg_goals', 'away_avg_goals', 'home_avg_conceded', 'away_avg_conceded', 'win_rate_diff', 'avg_goals_diff', 'avg_conceded_diff', 'home_advantage', 'is_friendly', 'is_worldcup', 'is_qualifier', 'home_elo', 'away_elo', 'elo_diff', 'elo_diff_squared', 'elo_gap', 'form_gap']

In [140]:
import numpy as np

In [141]:
def create_match_features(home_team,away_team):
    home = team_stats[home_team]
    away = team_stats[away_team]

    features_dict = {
        'home_win_rate':home['win_rate'],
        'away_win_rate' : away['win_rate'],
        'home_avg_goals' : home['avg_goals'],
        'away_avg_goals' : away['avg_goals'],
        'home_avg_conceded' : home['avg_conceded'],
        'away_avg_conceded' : away['avg_conceded'],
        'win_rate_diff' : home['win_rate'] - away['win_rate'],
        'avg_goals_diff' : home['avg_goals'] - away['avg_goals'],
        'avg_conceded_diff' : home['avg_conceded'] - away['avg_conceded'],
        'home_advantage' : 0,
        'is_friendly' : 0,
        'is_worldcup' : 1,
        'is_qualifier' : 0,
        'home_elo' : home['elo'],
        'away_elo' : away['elo'],
        'elo_diff' : home['elo'] - away['elo'],
        'elo_diff_squared' : (home['elo'] - away['elo'])**2,
        'elo_gap' : abs(home['elo'] - away['elo']),
        'form_gap' : abs(home['win_rate'] - away['win_rate'])
    }

    return pd.DataFrame([features_dict])[features]

In [142]:
def predict_match(home_team, away_team):

    X = create_match_features(home_team, away_team)

    probs = xgb.predict_proba(X)[0]

    return {
        "away_win": float(probs[0]),
        "draw": float(probs[1]),
        "home_win": float(probs[2])
    }

In [143]:
predict_match('Brazil','Argentina')

{'away_win': 0.5293121337890625,
 'draw': 0.2593892514705658,
 'home_win': 0.21129858493804932}

In [144]:
def show_prediction(team1,team2):
    probs = predict_match(team1,team2)
    print(f"{team1} vs {team2}")
    print()

    print(
        f"{team1} Win: "
        f"{probs["home_win"]:.2%}"
    )
    print(
        f"Draw : "
        f"{probs["draw"]:.2%}"
    )
    print(
        f"{team2} Win: "
        f"{probs["away_win"]:.2%}"
    )

In [145]:
show_prediction('Brazil','Argentina')

Brazil vs Argentina

Brazil Win: 21.13%
Draw : 25.94%
Argentina Win: 52.93%

In [146]:
show_prediction('Uruguay','Colombia')

Uruguay vs Colombia

Uruguay Win: 29.40%
Draw : 24.26%
Colombia Win: 46.35%

In [147]:
show_prediction('Norway','Senegal')

Norway vs Senegal

Norway Win: 41.29%
Draw : 19.24%
Senegal Win: 39.48%

In [148]:
show_prediction('France','Spain')

France vs Spain

France Win: 30.73%
Draw : 31.30%
Spain Win: 37.96%

In [149]:
show_prediction('France','Brazil')

France vs Brazil

France Win: 40.57%
Draw : 26.15%
Brazil Win: 33.29%

In [150]:
show_prediction('Brazil','Scotland')

Brazil vs Scotland

Brazil Win: 66.24%
Draw : 24.28%
Scotland Win: 9.48%

In [151]:
show_prediction('Morocco','Argentina')

Morocco vs Argentina

Morocco Win: 17.49%
Draw : 20.36%
Argentina Win: 62.15%

In [152]:
def simulate_match(home_team, away_team):

    X = create_match_features(
        home_team,
        away_team
    )

    probs = xgb.predict_proba(X)[0]

    outcome = np.random.choice(
        [0,1,2],
        p=probs
    )

    return outcome

In [153]:
for i in range(10):
    print(
        simulate_match(
            "Brazil",
            "France"
        )
    )

1
0
0
1
1
0
0
0
1
1

In [154]:
def simulate_knockout(team1, team2):

    result = simulate_match(team1, team2)

    if result == 2:
        return team1

    elif result == 0:
        return team2

    else:
        probs = predict_match(team1, team2)

        p = np.array([
            probs['home_win'],
            probs['away_win']
        ], dtype=np.float64)

        p /= p.sum()

        winner = np.random.choice(
            [team1, team2],
            p=p
        )

    return winner

In [155]:
for i in range(20):

    print(
        simulate_knockout(
            "Brazil",
            "France"
        )
    )

France
France
Brazil
France
France
Brazil
France
France
France
France
Brazil
France
France
France
France
Brazil
France
France
France
France

In [156]:
teams = [

    "Brazil",
    "Argentina",
    "France",
    "Morocco",
    "England",
    "Portugal",
    "Germany",
    "Spain"

]

In [157]:
qf1 = simulate_knockout(
    teams[0],
    teams[1]
)

qf2 = simulate_knockout(
    teams[2],
    teams[3]
)

qf3 = simulate_knockout(
    teams[4],
    teams[5]
)

qf4 = simulate_knockout(
    teams[6],
    teams[7]
)

In [158]:
sf1 = simulate_knockout(
    qf1,
    qf2
)

sf2 = simulate_knockout(
    qf3,
    qf4
)

In [159]:
champion = simulate_knockout(
    sf1,
    sf2
)

print(champion)

Morocco

In [160]:
def run_tournament(teams):

    current_round = teams.copy()

    while len(current_round) > 1:

        winners = []

        for i in range(0, len(current_round), 2):

            winner = simulate_knockout(
                current_round[i],
                current_round[i+1]
            )

            winners.append(winner)

        current_round = winners

    return current_round[0]

In [161]:
teams = [
    "Brazil",
    "Argentina",
    "France",
    "Spain",
    "England",
    "Portugal",
    "Germany",
    "Italy"
]

print(run_tournament(teams))

Argentina

In [162]:
print(run_tournament(teams))

England

In [163]:
print(run_tournament(teams))

France

In [164]:
print(run_tournament(teams))

Germany

In [165]:
print(run_tournament(teams))

England

In [166]:
print(run_tournament(teams))

Spain

In [167]:
from collections import Counter

champions = []

for _ in range(1000):
    champions.append(
        run_tournament(teams)
    )

counter = Counter(champions)

for team, count in counter.items():
    print(
        team,
        round(count / 1000 * 100, 2),
        "%"
    )

France 15.1 %
Argentina 11.8 %
Spain 17.7 %
Portugal 18.1 %
Germany 21.9 %
England 10.6 %
Brazil 3.7 %
Italy 1.1 %

In [168]:
pickle.dump(
    team_stats,
    open("team_stats.pkl","wb")
)